In [17]:
import os
import polars as pl

In [15]:
if not os.path.exists('data/train.csv'):
    !kaggle competitions download -c playground-series-s6e7
    !unzip playground-series-s6e7.zip -d data
    !rm playground-series-s6e7.zip
    !kaggle datasets download ziya07/college-student-health-behavior-dataset
    !unzip college-student-health-behavior-dataset.zip -d data

In [22]:
from mllabs.processor import PolarsLoader
ploader = PolarsLoader(predefined_types={'id': pl.Int64}, infer_schema_length=10000)
ploader.fit(['data/train.csv', 'data/test.csv', 'data/enhanced_student_health_dataset_50k.xls'])

PolarsLoader(infer_schema_length=10000, predefined_types={'id': Int64})

In [23]:
df_type = ploader.df_type_
df_type

,min,max,na,count,n_unique,dtype,f32,i32,i16,i8
feature,,,,,,,,,,
academic_pressure,NaN,NaN,0.0,50000.0,3.000000,String,False,False,False,False
alcohol_intake,NaN,NaN,0.0,50000.0,3.000000,String,False,False,False,False
bmi,16.0,35.000000,19854.0,1015987.0,17568.666667,Float64,True,True,True,True
calorie_expenditure,1200.0,3712.875140,75505.0,960336.0,17949.000000,Float64,True,True,True,False
diet_type,NaN,NaN,9859.0,1025982.0,3.666667,String,False,False,False,False
exercise_duration,0.0,120.000000,9859.0,1025982.0,16850.666667,Float64,True,True,True,True
gender,NaN,NaN,30533.0,1005308.0,3.666667,String,False,False,False,False
health_condition,NaN,NaN,0.0,740088.0,3.000000,String,False,False,False,False
heart_rate,50.0,117.020259,11190.0,1024651.0,16918.000000,Float64,True,True,True,True
id,0.0,985840.000000,0.0,985841.0,492920.500000,Int64,True,True,False,False
mental_health_status,NaN,NaN,0.0,50000.0,3.000000,String,False,False,False,False
physical_activity_level,NaN,NaN,52316.0,983525.0,3.666667,String,False,False,False,False
screen_time,0.0,12.000000,0.0,50000.0,49647.000000,Float64,True,True,True,True
sitting_time,2.0,16.000000,0.0,50000.0,49919.000000,Float64,True,True,True,True
sleep_duration,3.0,10.000000,108570.0,927271.0,16697.333333,Float64,True,True,True,True
sleep_quality,NaN,NaN,83330.0,952511.0,3.666667,String,False,False,False,False
smoking_alcohol,NaN,NaN,40831.0,945010.0,4.000000,String,False,False,False,False
smoking_status,NaN,NaN,0.0,50000.0,3.000000,String,False,False,False,False
social_relationships,NaN,NaN,0.0,50000.0,3.000000,String,False,False,False,False
step_count,1000.0,14999.000000,19880.0,1015961.0,12868.000000,Int64,True,True,True,False
stress_level,NaN,NaN,118301.0,917540.0,3.666667,String,False,False,False,False
student_id,1000.0,2999.000000,0.0,50000.0,2000.000000,Int64,True,True,True,False
timestamp,NaN,NaN,0.0,50000.0,50000.000000,String,False,False,False,False
water_intake,0.5,5.000000,62110.0,973731.0,16804.000000,Float64,True,True,True,True

In [25]:
ploader.transform('data/train.csv')

shape: (690_088, 15)
┌────────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬────────┐
│ id     ┆ health_con ┆ sleep_dura ┆ heart_rate ┆ … ┆ sleep_qual ┆ physical_a ┆ smoking_a ┆ gender │
│ ---    ┆ dition     ┆ tion       ┆ ---        ┆   ┆ ity        ┆ ctivity_le ┆ lcohol    ┆ ---    │
│ i64    ┆ ---        ┆ ---        ┆ f32        ┆   ┆ ---        ┆ vel        ┆ ---       ┆ cat    │
│        ┆ cat        ┆ f32        ┆            ┆   ┆ cat        ┆ ---        ┆ cat       ┆        │
│        ┆            ┆            ┆            ┆   ┆            ┆ cat        ┆           ┆        │
╞════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪════════╡
│ 0      ┆ unhealthy  ┆ 5.22       ┆ 70.599998  ┆ … ┆ average    ┆ sedentary  ┆ yes       ┆ female │
│ 1      ┆ at-risk    ┆ 5.53       ┆ 71.300003  ┆ … ┆ average    ┆ moderate   ┆ yes       ┆ other  │
│ 2      ┆ unhealthy  ┆ 5.29       ┆ 75.400002  ┆ … ┆ poor       ┆ active     ┆ yes       ┆ male   │
│ 3      ┆ unhealthy  ┆ 4.7        ┆ 77.199997  ┆ … ┆ average    ┆ active     ┆ occasiona ┆ female │
│        ┆            ┆            ┆            ┆   ┆            ┆            ┆ l         ┆        │
│ 4      ┆ at-risk    ┆ 7.23       ┆ 73.400002  ┆ … ┆ average    ┆ sedentary  ┆ null      ┆ male   │
│ …      ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …      │
│ 690083 ┆ at-risk    ┆ 6.31       ┆ 69.699997  ┆ … ┆ poor       ┆ active     ┆ yes       ┆ female │
│ 690084 ┆ at-risk    ┆ 5.78       ┆ 54.0       ┆ … ┆ average    ┆ moderate   ┆ no        ┆ male   │
│ 690085 ┆ fit        ┆ 7.64       ┆ 85.699997  ┆ … ┆ average    ┆ active     ┆ no        ┆ male   │
│ 690086 ┆ at-risk    ┆ 6.74       ┆ 73.0       ┆ … ┆ average    ┆ active     ┆ yes       ┆ male   │
│ 690087 ┆ at-risk    ┆ 5.55       ┆ 69.300003  ┆ … ┆ average    ┆ moderate   ┆ yes       ┆ male   │
└────────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴────────┘